INSERT INTO GMR_USER (ID, NAME, LOGIN, PASSWORD, EMAIL) VALUES (1, 'Joao', 'jh', '123456', 'joao@gmail.com');

ALTER SEQUENCE GMR_USER_ID_SEQ RESTART WITH 2;

INSERT INTO GMR_PERFIL (ID, DESCRIPTION) VALUES (1, 'Engenheiro de Software');

ALTER SEQUENCE GMR_PERFIL_SEQ RESTART WITH 2;