INSERT INTO GMR_USER (ID, NAME, LOGIN, PASSWORD, EMAIL) VALUES (1, 'Joao', 'jh', '123456', 'joao@gmail.com');
INSERT INTO GMR_USER (ID, NAME, LOGIN, PASSWORD, EMAIL) VALUES (2, 'Henrique', 'hh', '123456', 'Henrique@gmail.com');

ALTER SEQUENCE GMR_USER_ID_SEQ RESTART WITH 3;

INSERT INTO GMR_PERFIL (ID, DESCRIPTION) VALUES (1, 'Engenheiro de Software');
INSERT INTO GMR_PERFIL (ID, DESCRIPTION) VALUES (2, 'Adiministrador');
INSERT INTO GMR_PERFIL (ID, DESCRIPTION) VALUES (3, 'Recepicionista');

ALTER SEQUENCE GMR_PERFIL_SEQ RESTART WITH 4;

INSERT INTO GMR_RESOURCE (ID, NAME, KEY) VALUES (1, 'Tela de Usuario', 'Usuario');
INSERT INTO GMR_RESOURCE (ID, NAME, KEY) VALUES (2, 'Tela de Prfil', 'Perfil');
INSERT INTO GMR_RESOURCE (ID, NAME, KEY) VALUES (3, 'Tela de Recurso', 'Recurso');

ALTER SEQUENCE GMR_RESOURCE_ID_SEQ RESTART WITH 4;
